name: Sonar

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
           Dsonar.inclusions=server.ts,frontend/src/app/app.routing.ts,frontend/src/app/search-result/search-result.component.ts,,routes/login.ts,routes/search.ts,routes/updateProductReviews.ts,data/static/codefixes/xssBonusChallenge_1_correct.ts,data/static/codefixes/unionSqlInjectionChallenge_2_correct.ts,/data/static/codefixes/accessLogDisclosureChallenge_1_correct.ts,data/static/codefixes/accessLogDisclosureChallenge_1_correct.ts,data/static/codefixes/adminSectionChallenge_1_correct.ts,data/static/codefixes/dbSchemaChallenge_2_correct.ts
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
